services:
  grafana:
    image: grafana/grafana:12.1.1
    container_name: grafana
    restart: unless-stopped
    cpus: '2.0'
    ports:
      - '3100:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring

volumes:
  grafana_data:

networks:
  monitoring:
